config/routes.rb
Contented::Application.routes.draw do
  devise_for :users
  resources :users
  match '/writers/:id' => "users#show", :as => 'writer'
  match '/writers' => "pages#writers", :as => 'writers_page'

  resources :articles do
    resources :comments
    collection do
      get "uncategorized"
    end
  end

  match '/feed' => 'articles#feed', :as => :feed, :defaults => { :format => 'atom' }
  match '/search' => 'articles#search', :as => :search

  resources :categories do
    resources :articles
  end

  resources :comments

  get "home/index"

  root :to => "articles#index"
end

app/models/article.rb
class Article < ActiveRecord::Base
  # associations
  has_many :comments, :dependent => :destroy
  has_many :attachments, :as => :attachable
  belongs_to :featured_image, :class_name => "Attachment"
  belongs_to :category
  belongs_to :user

  accepts_nested_attributes_for :attachments, :allow_destroy => true

  # validations
  validates_presence_of :title, :allow_blank => false
  validates_presence_of :body, :allow_blank => false

  scope :uncategorized, where(:category_id => nil)
  scope :published, where(:published => true)

  extend FriendlyId
  friendly_id :title, :use => :slugged
 
  define_index do
    indexes title, :sortable => true
    indexes body
    indexes teaser
    has user_id, category_id, created_at, updated_at

    set_property :field_weights => {
      :title => 5,
      :body    => 2,
      :teaser => 1
    }
  end

  def body_markdown
    require 'rdiscount'
    RDiscount.new(body).to_html.html_safe
  end

  def category_name
    categorized? ? category[:title] : "Uncategorized"
  end

  def author_name
    user.full_name rescue nil
  end

  def categorized?
    category ? true : false
  end

  def created_date
    created_at.strftime("%Y-%m-%d") rescue nil
  end

  def published_state
    published ? "Published" : "Unpublished"
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :fetch_article, :only => [:show, :update, :edit, :destroy]

  def index
    if Ability.new(current_user).can_view_rough_drafts
      @articles = Article.order "created_at desc"
    else 
      @articles = Article.published.order "created_at desc"
    end

    respond_to do |format|
      format.html     # index.html.erb
      format.xml  { render :xml => @articles }
    end
  end

  def show
    authorize! :view, @article
    @comments = @article.comments
    @comment = Comment.new :article_id => @article.id
  end

  def search
    if Ability.new(current_user).can_view_rough_drafts
      @articles = Article.search params[:keyword]
    else
      @articles = Article.search params[:keyword], :conditions => 
        { :published => true }
    end
  end

  def uncategorized
    @articles = Article.uncategorized
  end

  def edit
    authorize! :edit, @article
    5.times { @article.attachments.build }
  end

  def feed
    @articles = Article.published.order("created_at desc").limit(10)
    respond_to do |format|
      format.atom
    end
  end

  def create
    authorize! :create, Article
    @article = Article.create params[:article].merge(:user_id => current_user[:id])
    if @article.valid?
      flash[:notice] = "#{@article.title} was successfully created"
      redirect_to articles_path
    else
      flash[:warning] = "Article creation failed"
      render :action => "new"
    end
  end

  def update
    authorize! :update, @article
    @article.update_attributes params[:article]
    if @article.valid?
      flash[:notice] = "#{@article[:title]} was saved to category #{@article.category_name}"
      redirect_to(article_path(@article))
    else
      render :action => "new"
    end
  end

  def new
    authorize! :build, Article
    @article = Article.new
    5.times { @article.attachments.build }
  end

  def destroy
    authorize! :destroy, @article
    @article.destroy
    flash[:notice] = "Article was successfully destroyed"
    redirect_to articles_path
  end

  protected
  def fetch_article
    @article = Article.find params[:id]
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def comments_link(article)
    extend ActionView::Helpers::TextHelper
    link_to(pluralize(article.comments.count, "comment"), (article_path(article) + "#comments"), :class => "comments")
  end
end

app/views/articles/_article.html.haml
- if can? :view, article
  %div[article]{:class => cycle("odd", "even", :name => "articles")}
    = link_to article.title, article_path(article), :class => "title"
    .info
      - if can? :edit, article
        .published= article.published_state
      .author.date.active_category!= "published by #{article.author_name} in category #{category_link(article)} on #{article.created_date}"
    .clear
    .comments= comments_link(article)
    - if article.featured_image
      .featured_image= image_tag article.featured_image.asset.large.url
    .teaser= markdown(article.teaser)
    .clear

app/views/articles/_form.html.haml
= stylesheet_link_tag "articles/shared"
= stylesheet_link_tag "attachments/shared"

= javascript_include_tag "views/attachments/images"

.resource_links
  = link_to "Cancel", @article, :id => "cancel_editing"
= nested_form_for @article, :html => { :multipart => true } do |f|
  = f.error_messages
  .fields
    = f.label :title
    = f.text_field :title
  .fields
    = f.label :published, "Published?"
    = f.check_box :published
  .fields
    = f.label :category
    = f.collection_select :category_id, Category.all, :id, :title, {:include_blank => "Uncategorized"}
  .fields
    = f.label :featured_image_id, "Featured Image"
    = f.collection_select :featured_image_id, @article.attachments.all, :id, :asset, {:include_blank => "None"}
  .fields
    = f.label :teaser
    = f.text_area :teaser
  .fields
    = f.label :body
    = f.text_area :body
  

  = f.fields_for :attachments do |attachment_fields|
    - if attachment_fields.object.new_record?
      .fields
        = attachment_fields.label :asset, ""
        = attachment_fields.file_field :asset
  = f.fields_for :attachments do |attachment_fields|
    - unless attachment_fields.object.new_record?
      %div[attachment_fields.object]
        .image
          .image_name= link_to attachment_fields.object.asset.url, attachment_fields.object.asset.url
          = link_to image_tag(attachment_fields.object.asset.small.url), attachment_fields.object.asset.url
          %br
          = attachment_fields.label :_destroy
          = attachment_fields.check_box :_destroy

        .image_controls
          %button.add_image{ :url => attachment_fields.object.asset.url } Original
          = link_to "(view)", attachment_fields.object.asset.url
          %br
          %button.add_image{ :url => attachment_fields.object.asset.large.url } Large
          = link_to "(view)", attachment_fields.object.asset.large.url, :class => "image_link large"
          %br
          %button.add_image{ :url => attachment_fields.object.asset.medium.url } Medium
          = link_to "(view)", attachment_fields.object.asset.medium.url, :class => "image_link medium"
          %br
          %button.add_image{ :url => attachment_fields.object.asset.small.url } Small
          = link_to "(view)", attachment_fields.object.asset.small.url, :class => "image_link small"
          %br
          %button.add_image{ :url => attachment_fields.object.asset.thumb.url } Thumb
          = link_to "(view)", attachment_fields.object.asset.thumb.url, :class => "image_link thumb"
    .clear
  .fields
    = f.submit

app/views/articles/edit.html.haml
%h2 Edit Article
= render :partial => "form"

app/views/articles/index.html.haml
= stylesheet_link_tag "articles/shared"
= render @articles

app/views/articles/new.html.haml
%h2 New Article
= render :partial => "form"

app/views/articles/search.html.haml
= stylesheet_link_tag "articles/shared"
%h2 Search
= "Found #{pluralize(@articles.count, 'article')} with keyword \"#{params[:keyword]}\""
= render @articles

app/views/articles/show.html.haml
= stylesheet_link_tag "articles/shared"

%div[@article]
  - if @article.categorized?
    .active_category= link_to @article.category_name, @article.category
  - else
    .active_category= link_to "Uncategorized", uncategorized_articles_path
  = link_to @article.title, @article, :class => "title"
  .resource_links
    -#- if can? :view_published_articles
    .published= @article.published_state
    - if can? :destroy, @article
      = button_to "Delete", @article, :method => :delete, :class => :destroy
    - if can? :edit, @article
      = link_to "Edit", edit_article_path(@article), :class => "edit"
  - if @article.featured_image
    .featured_image= image_tag @article.featured_image.asset.large.url
  .body
    != @article.body_markdown

#comments
  %h2 Comments
  = render :partial => @comments
  - if current_user and can? :create, @comment
    = form_for [@article, @comment] do |f|
      .fields
        = f.label :body, "Comment"
        = f.text_area :body
      = f.submit

app/views/articles/uncategorized.html.haml
= stylesheet_link_tag "articles/shared"
%h2 Uncategorized Articles
= render @articles

app/views/articles/upload_jquery.html.haml
%link#theme{:href => "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/themes/base/jquery-ui.css", :rel => "stylesheet"}/
<%= stylesheet_link_tag 'jquery.fileupload-ui' %>
#fileupload
  <%= form_for Picture.new, :html => { :multipart => true } do |f| %>
  .fileupload-buttonbar
    %label.fileinput-button
      %span Add files...
      <%= f.file_field :avatar %>
    %button.start{:type => "submit"} Start upload
    %button.cancel{:type => "reset"} Cancel upload
    %button.delete{:type => "button"} Delete files
  <% end %>
  .fileupload-content
    %table.files
    .fileupload-progressbar
%script#template-upload{:type => "text/x-jquery-tmpl"}
  <tr class="template-upload{{if error}} ui-state-error{{/if}}">
  <td class="preview"></td>
  <td class="name">${name}</td>
  <td class="size">${sizef}</td>
  {{if error}}
  <td class="error" colspan="2">Error:
  {{if error === 'custom_failure'}}Custom Error Message
  {{else}}${error}
  {{/if}}
  </td>
  {{else}}
  <td class="progress"><div></div></td>
  <td class="start"><button>Start</button></td>
  {{/if}}
  <td class="cancel"><button>Cancel</button></td>
  </tr>
%script#template-download{:type => "text/x-jquery-tmpl"}
  <tr class="template-download{{if error}} ui-state-error{{/if}}">
  {{if error}}
  <td></td>
  <td class="name">${name}</td>
  <td class="size">${sizef}</td>
  <td class="error" colspan="2">Error:
  {{if error === 1}}File exceeds upload_max_filesize (php.ini directive)
  {{else}}${error}
  {{/if}}
  </td>
  {{else}}
  <td class="preview">
  {{if thumbnail_url}}
  <a href="${url}" target="_blank"><img src="${thumbnail_url}"></a>
  {{/if}}
  </td>
  <td class="name">
  <a href="${url}"{{if thumbnail_url}} target="_blank"{{/if}}>${name}</a>
  </td>
  <td class="size">${sizef}</td>
  <td colspan="2"></td>
  {{/if}}
  <td class="delete">
  <button data-type="${delete_type}" data-url="${delete_url}">Delete</button>
  </td>
  </tr>
%script{:src => "//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"}
%script{:src => "//ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/jquery-ui.min.js"}
%script{:src => "//ajax.aspnetcdn.com/ajax/jquery.templates/beta1/jquery.tmpl.min.js"}
<%= javascript_include_tag 'jquery.iframe-transport' %>
<%= javascript_include_tag 'jquery.fileupload' %>
<%= javascript_include_tag 'jquery.fileupload-ui' %>
%script{:charset => "utf-8", :type => "text/javascript"}
  $(function () {
  \// Initialize the jQuery File Upload widget:
  $('#fileupload').fileupload();
  \//
  \// Load existing files:
  $.getJSON($('#fileupload form').prop('action'), function (files) {
  var fu = $('#fileupload').data('fileupload');
  fu._adjustMaxNumberOfFiles(-files.length);
  fu._renderDownload(files)
  \.appendTo($('#fileupload .files'))
  \.fadeIn(function () {
  \// Fix for IE7 and lower:
  $(this).show();
  });
  });
  
  \// Open download dialogs via iframes,
  \// to prevent aborting current uploads:
  $('#fileupload .files a:not([target^=_blank])').live('click', function (e) {
  e.preventDefault();
  $('<iframe style="display:none;"></iframe>')
  \.prop('src', this.href)
  \.append

app/views/articles/view.html.haml
%h1 Articles#view
%p Find me in app/views/articles/view.html.haml