config/routes.rb
Contented::Application.routes.draw do
  devise_for :users
  resources :users
  match '/writers/:id' => "users#show", :as => 'writer'
  match '/writers' => "pages#writers", :as => 'writers_page'

  resources :articles do
    resources :comments
    collection do
      get "uncategorized"
    end
  end

  match '/feed' => 'articles#feed', :as => :feed, :defaults => { :format => 'atom' }
  match '/search' => 'articles#search', :as => :search

  resources :categories do
    resources :articles
  end

  resources :comments

  get "home/index"

  root :to => "articles#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    @user = user || User.new
    set_abilities_by_role
  end

  def set_abilities_by_role
    case @user.role
    when "admin"
      can :manage, :all
    when "reader"
      can_view_published_article
      can_manage_self
      can :create, Comment
      can_delete_own_comment
    end
  end

  def can_view_rough_drafts
    can [:view], Article, :role => "admin"
  end

  def can_view_published_article
    can [:view], Article, :published => true
  end

  def can_manage_self
    can [:manage], User, ["id = ?", @user.id] do |current_user|
      current_user.id == @user.id
    end
  end

  def can_delete_own_comment
    can [:delete], Comment do |comment|
      comment.user_id == @user.id and not comment.user_id.nil?
    end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  # associations
  has_many :comments, :dependent => :destroy
  has_many :attachments, :as => :attachable
  belongs_to :featured_image, :class_name => "Attachment"
  belongs_to :category
  belongs_to :user

  accepts_nested_attributes_for :attachments, :allow_destroy => true

  # validations
  validates_presence_of :title, :allow_blank => false
  validates_presence_of :body, :allow_blank => false

  scope :uncategorized, where(:category_id => nil)
  scope :published, where(:published => true)

  extend FriendlyId
  friendly_id :title, :use => :slugged
 
  define_index do
    indexes title, :sortable => true
    indexes body
    indexes teaser
    has user_id, category_id, created_at, updated_at

    set_property :field_weights => {
      :title => 5,
      :body    => 2,
      :teaser => 1
    }
  end

  def body_markdown
    require 'rdiscount'
    RDiscount.new(body).to_html.html_safe
  end

  def category_name
    categorized? ? category[:title] : "Uncategorized"
  end

  def author_name
    user.full_name rescue nil
  end

  def categorized?
    category ? true : false
  end

  def created_date
    created_at.strftime("%Y-%m-%d") rescue nil
  end

  def published_state
    published ? "Published" : "Unpublished"
  end
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  include Rails.application.routes.url_helpers
  belongs_to :attachable, :polymorphic => true
  mount_uploader :asset, AssetUploader

  def to_jq_upload
    {
      "name" => read_attribute(:asset),
      "size" => asset.size,
      "url" => asset.url,
      "thumbnail_url" => asset.thumb.url,
      "delete_url" => asset_path(:id => id),
      "delete_type" => "DELETE" 
    }
  end
end

app/models/asset_link.rb
class AssetLink < ActiveRecord::Base
  belongs_to :asset
  belongs_to :attachable, :polymorphic => true
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :attachable, :polymorphic => true
  mount_uploader :asset, AssetUploader

  Attachment.before_destroy :remove_files

  def store_dir
    "public/uploads/attachment/asset/#{id}"
  end

  def remove_files
    require 'fileutils'
    FileUtils.rm_rf store_dir
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  # associations
  has_many :articles

  # validations
  validates :title, :presence => true

  # callbacks
  after_destroy :remove_article_categories

  extend FriendlyId
  friendly_id :title, :use => :slugged

  def recent_articles(count=3)
    articles.order("created_at DESC").take count
  end

  protected
  def remove_article_categories
    Article.where(:category_id => id).each do |article|
      article.update_attributes :category_id => nil
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  validates :body, :presence => true
  validates :article_id, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :omniauthable, :encryptable
  devise :database_authenticatable, :registerable, :timeoutable, :lockable,
         :recoverable, :rememberable, :trackable, :validatable, :token_authenticatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :first_name, :last_name, :role, :display_name,
    :password, :password_confirmation, :remember_me

  has_many :articles

  scope :with_published_articles, lambda {
    where("id in (select DISTINCT user_id from articles where published = ?)", true)
  }

  extend FriendlyId
  friendly_id :full_name, :use => :slugged

  def full_name
    "#{first_name} #{last_name}"
  end

  ROLES = %w[ reader admin ]
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  def index
    @assets = Asset.all
    render :json => @assets.collect { |p| p.to_jq_upload }.to_json
  end

  def create
    @asset = Asset.new(params[:asset])
    if @asset.save
      render :json => [@asset.to_jq_upload].to_json
    else 
      render :json => [{:error => "custom_failure"}], :status => 304
    end
  end

  def destroy
    @asset = Asset.find(params[:id])
    @asset.destroy
    render :json => true
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def writers
    @writers = User.with_published_articles.order "last_name asc"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :fetch_user, :except => [:index]

  def index
    @users = User.all
    authorize! :index, @users
  end

  def edit
  end

  def show
  end

  def update
    if @user.update_attributes filtered_params
      flash[:notice] = "User '#{@user.email}' was successfully updated."
      redirect_to users_path
    else
      render :action => "edit"
    end
  end

  private

  def fetch_user
    @user = User.find params[:id]
  end

  def filtered_params
    ParamFilter.new(params[:user]).filter_empty_passwords
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_flash
    [:notice, :warning, :alert].collect do |key|
      content_tag :div, flash[key], {:class => "flash #{key}"} if flash[key]
    end.compact.join
  end

  def markdown(text)
    require 'rdiscount'
    RDiscount.new(text).to_html.html_safe rescue ""
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def comments_link(article)
    extend ActionView::Helpers::TextHelper
    link_to(pluralize(article.comments.count, "comment"), (article_path(article) + "#comments"), :class => "comments")
  end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def category_link(article)
    if article.categorized?
      link_to article.category_name, article.category
    else
      link_to "Uncategorized", uncategorized_articles_path
    end
  end
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/navigation_helper.rb
module NavigationHelper
  def active_on(klass, controllers={})
    active_action?(controllers) ? "#{klass} active" : klass
  end

  require 'action_parser'
  def active_action?(controllers={})
    ActionParser.new(controller_name, action_name, controllers).active?
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/assets/_asset.html.haml
-# app/views/assets/_asset.html.haml

.asset[asset]
  = image_tag asset.image_url(:thumb) if asset.image?
  = link_to "Delete", article_asset_path(@article, asset), :method => :delete, :confirm => "Are you sure?", :remote => :true

app/views/assets/destroy.js.erb
<%- if flash[:error].blank? -%>
  $('#asset_<%= @asset.id %>').remove();
<%- end -%>

app/views/users/_links.html.haml
.form_links
    -# = link_to "Sign in", new_session_path(resource_name)
    -# = link_to "Sign up", new_registration_path(resource_name)
    -# = link_to "Forgot your password?", new_password_path(resource_name)
    -# = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
    -# = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)

app/views/users/_user.html.haml
%tr{:class => cycle("odd", "even"), :name => "user rows"}[user]
  %td.email= link_to user.email, edit_user_path(user), :class => "edit"
  %td.role= user.role
  %td.first_name= user.first_name
  %td.last_name= user.last_name
  %td.last_sign_in_at= user.last_sign_in_at
  %td.last_sign_in_ip= user.last_sign_in_ip
  %td.failed_attempts= user.failed_attempts

app/views/users/_writer.html.haml
%div[writer]
  = link_to writer.full_name, writer_path(writer)
  .biography= writer.biography

app/views/users/edit.html.haml
%h2
  Edit User
= form_for @user do |f|
  = render :partial => "shared/error_messages", :locals => { :target => @user }
  .fields
    = f.label :email
    = f.text_field :email
  .fields
    = f.label :role
    = f.select :role, User::ROLES
  .fields
    = f.label :first_name
    = f.text_field :first_name
  .fields
    = f.label :last_name
    = f.text_field :last_name
  .fields
    = f.label :display_name
    %i (name that other users will see you by)
    = f.text_field :display_name

  %br
  .fields
    = f.label :password
    %i (leave blank if you don't want to change it)
    = f.password_field :password
  .fields
    = f.label :password_confirmation
    = f.password_field :password_confirmation
 
  .fields= f.submit "Update"

- if current_user and can?(:delete, current_user)
  %br
  %h4 Tired of fighting the good fight?
  -# %h4= link_to "Cancel your account.", registration_path(resource_name), :confirm => "Are you sure?", :method => :delete

app/views/users/index.html.haml
= stylesheet_link_tag "users/index"

%table#users
  %thead
    %th Email
    %th Role
    %th First
    %th Last
    %th Last Sign-In
    %th Last IP
    %th Failed Attempts
  %tbody
    = render @users