config/routes.rb
Contented::Application.routes.draw do
  devise_for :users
  resources :users
  match '/writers/:id' => "users#show", :as => 'writer'
  match '/writers' => "pages#writers", :as => 'writers_page'

  resources :articles do
    resources :comments
    collection do
      get "uncategorized"
    end
  end

  match '/feed' => 'articles#feed', :as => :feed, :defaults => { :format => 'atom' }
  match '/search' => 'articles#search', :as => :search

  resources :categories do
    resources :articles
  end

  resources :comments

  get "home/index"

  root :to => "articles#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    @user = user || User.new
    set_abilities_by_role
  end

  def set_abilities_by_role
    case @user.role
    when "admin"
      can :manage, :all
    when "reader"
      can_view_published_article
      can_manage_self
      can :create, Comment
      can_delete_own_comment
    end
  end

  def can_view_rough_drafts
    can [:view], Article, :role => "admin"
  end

  def can_view_published_article
    can [:view], Article, :published => true
  end

  def can_manage_self
    can [:manage], User, ["id = ?", @user.id] do |current_user|
      current_user.id == @user.id
    end
  end

  def can_delete_own_comment
    can [:delete], Comment do |comment|
      comment.user_id == @user.id and not comment.user_id.nil?
    end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  # associations
  has_many :comments, :dependent => :destroy
  has_many :attachments, :as => :attachable
  belongs_to :featured_image, :class_name => "Attachment"
  belongs_to :category
  belongs_to :user

  accepts_nested_attributes_for :attachments, :allow_destroy => true

  # validations
  validates_presence_of :title, :allow_blank => false
  validates_presence_of :body, :allow_blank => false

  scope :uncategorized, where(:category_id => nil)
  scope :published, where(:published => true)

  extend FriendlyId
  friendly_id :title, :use => :slugged
 
  define_index do
    indexes title, :sortable => true
    indexes body
    indexes teaser
    has user_id, category_id, created_at, updated_at

    set_property :field_weights => {
      :title => 5,
      :body    => 2,
      :teaser => 1
    }
  end

  def body_markdown
    require 'rdiscount'
    RDiscount.new(body).to_html.html_safe
  end

  def category_name
    categorized? ? category[:title] : "Uncategorized"
  end

  def author_name
    user.full_name rescue nil
  end

  def categorized?
    category ? true : false
  end

  def created_date
    created_at.strftime("%Y-%m-%d") rescue nil
  end

  def published_state
    published ? "Published" : "Unpublished"
  end
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  include Rails.application.routes.url_helpers
  belongs_to :attachable, :polymorphic => true
  mount_uploader :asset, AssetUploader

  def to_jq_upload
    {
      "name" => read_attribute(:asset),
      "size" => asset.size,
      "url" => asset.url,
      "thumbnail_url" => asset.thumb.url,
      "delete_url" => asset_path(:id => id),
      "delete_type" => "DELETE" 
    }
  end
end

app/models/asset_link.rb
class AssetLink < ActiveRecord::Base
  belongs_to :asset
  belongs_to :attachable, :polymorphic => true
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :attachable, :polymorphic => true
  mount_uploader :asset, AssetUploader

  Attachment.before_destroy :remove_files

  def store_dir
    "public/uploads/attachment/asset/#{id}"
  end

  def remove_files
    require 'fileutils'
    FileUtils.rm_rf store_dir
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  # associations
  has_many :articles

  # validations
  validates :title, :presence => true

  # callbacks
  after_destroy :remove_article_categories

  extend FriendlyId
  friendly_id :title, :use => :slugged

  def recent_articles(count=3)
    articles.order("created_at DESC").take count
  end

  protected
  def remove_article_categories
    Article.where(:category_id => id).each do |article|
      article.update_attributes :category_id => nil
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  validates :body, :presence => true
  validates :article_id, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :omniauthable, :encryptable
  devise :database_authenticatable, :registerable, :timeoutable, :lockable,
         :recoverable, :rememberable, :trackable, :validatable, :token_authenticatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :first_name, :last_name, :role, :display_name,
    :password, :password_confirmation, :remember_me

  has_many :articles

  scope :with_published_articles, lambda {
    where("id in (select DISTINCT user_id from articles where published = ?)", true)
  }

  extend FriendlyId
  friendly_id :full_name, :use => :slugged

  def full_name
    "#{first_name} #{last_name}"
  end

  ROLES = %w[ reader admin ]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def writers
    @writers = User.with_published_articles.order "last_name asc"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :fetch_user, :except => [:index]

  def index
    @users = User.all
    authorize! :index, @users
  end

  def edit
  end

  def show
  end

  def update
    if @user.update_attributes filtered_params
      flash[:notice] = "User '#{@user.email}' was successfully updated."
      redirect_to users_path
    else
      render :action => "edit"
    end
  end

  private

  def fetch_user
    @user = User.find params[:id]
  end

  def filtered_params
    ParamFilter.new(params[:user]).filter_empty_passwords
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_flash
    [:notice, :warning, :alert].collect do |key|
      content_tag :div, flash[key], {:class => "flash #{key}"} if flash[key]
    end.compact.join
  end

  def markdown(text)
    require 'rdiscount'
    RDiscount.new(text).to_html.html_safe rescue ""
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def comments_link(article)
    extend ActionView::Helpers::TextHelper
    link_to(pluralize(article.comments.count, "comment"), (article_path(article) + "#comments"), :class => "comments")
  end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def category_link(article)
    if article.categorized?
      link_to article.category_name, article.category
    else
      link_to "Uncategorized", uncategorized_articles_path
    end
  end
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/navigation_helper.rb
module NavigationHelper
  def active_on(klass, controllers={})
    active_action?(controllers) ? "#{klass} active" : klass
  end

  require 'action_parser'
  def active_action?(controllers={})
    ActionParser.new(controller_name, action_name, controllers).active?
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_feeds.html.haml
#feeds
  = link_to "RSS/ATOM", feed_path

app/views/layouts/_search.html.haml
= stylesheet_link_tag "search"
#search
  = form_tag search_path do
    = text_field_tag "keyword"
    = submit_tag "Search"

app/views/layouts/_session.html.haml
#session
  - if user_signed_in?
    = link_to "My Account (#{current_user[:email]})", edit_user_registration_path, :class => "title"
    = link_to "Sign Out", destroy_user_session_path, :class => "title"
  - else
    = link_to "Sign In", new_user_session_path, :class => "title"
    = link_to "Register", new_user_registration_path, :class => "title"

app/views/layouts/application.html.haml
%html
  %head
    %title Contented
    = stylesheet_link_tag "layouts/application"
    = stylesheet_link_tag "errors"
    = stylesheet_link_tag "forms"
    = stylesheet_link_tag "nav"
    = stylesheet_link_tag "flash"
    = stylesheet_link_tag "http://fonts.googleapis.com/css?family=Arvo|Bitter|Brawler|Copse|Droid+Serif|Lora|Merriweather|Ubuntu|Vollkorn"
    = javascript_include_tag "jquery"
    = javascript_include_tag "plugins/autofade.jquery"
    = javascript_include_tag "plugins/autoscroll.jquery"
    = javascript_include_tag "application"
    = javascript_include_tag "flash"
    = javascript_include_tag "nested_form"
    = csrf_meta_tag
  %body
    = auto_discovery_link_tag :atom, feed_path
    #sidebar
      %a#branding{:href => "/"}
        .title Contented
        .subtitle Keep your content Happy.
      = render :partial => "layouts/search"
      = render :partial => "layouts/session"
      = render :partial => "layouts/feeds"
      #categories= render :partial => "categories/sidebar"
    #navigation= render :partial => "nav/primary"
    #flash!= show_flash
    #content
      #primary= yield

app/views/nav/_category.html.haml
= link_to "#{category.title} (#{category.articles.count})", category, :class => "category"

app/views/nav/_primary.html.haml
.section.home
  = link_to "Home", root_path, :class => active_on("home title", :pages => [:homepage])

.section.articles
  = link_to "Articles", articles_path, :class => active_on("articles title", :articles => true)
  - if can? :create, Article
    = link_to "New", new_article_path, :class => "new_article"

.section.categories
  = link_to "Categories", categories_path, :class => active_on("categories title", :categories => true)
  - if can? :create, Category
    = link_to "New", new_category_path, :class => "new_category"

.section.writers
  = link_to "Writers", writers_page_path, :class => active_on("writers title", :writers => true)

-# .section.testimonials
-#   = link_to "Testimonials", testimonials_path, :class => active_on("testimonials title", :testimonials => true)
-#   - if current_user and can?(:create, Testimonial)
-#     = link_to "New", new_article_path

-# .section.links
-#   = link_to "Links", links_path, :class => active_on("links title", :links => true)
-#   - if current_user and can?(:create, Link)
-#     = link_to "New", new_link_path

app/views/pages/writers.html.haml
#writers
  %h2 Writers
  -# - @writers.each do |writer|
  -#   = link_to user_path(writer), writer.full_name
  -#   = writer.biography

  = render :partial => "users/writer", :collection => @writers

app/views/shared/_error.html.haml
%li= message

app/views/shared/_error_messages.html.haml
- if target.errors.any?
  #errorExplanation
    %h2= "#{pluralize(target.errors.count, "error")} prevented this #{target.class.to_s.downcase} from being saved."
    %ul
      - target.errors.full_messages.each do |message|
        = render :partial => "shared/error", :locals => { :message => message }

app/views/shared/_form_links.html.haml
.form_links
    -# = link_to "Sign in", new_session_path(resource_name)
    -# = link_to "Sign up", new_registration_path(resource_name)
    -# = link_to "Forgot your password?", new_password_path(resource_name)
    -# = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
    -# = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)